from .analytic_linear import infer_class_label_from_last_bias, invert_first_linear_gradient
from .gradient_inversion import (
    AttackResult,
    GradientInversionAttack,
    gradient_matching_loss,
    leak_gradients,
)
from .gradient_release import (
    GradientRelease,
    GradientReleaseSpec,
    clip_gradient_tuple,
    gradient_tuple_l2_norm,
    last_biased_linear_parameter_indices,
    quantize_gradient_tuple,
    release_gradients,
)
from .head_representation import (
    HeadRepresentationAttackResult,
    HeadRepresentationInversionAttack,
    LinearHeadLeakageReport,
    capture_final_linear_input,
    find_last_biased_linear,
    recover_single_effective_head_input,
)
from .learned_quantile_initializer import (
    LEARNED_QUANTILE_REFERENCE,
    GradientFeatureNormalizer,
    GradientToQuantileNetwork,
    QuantileInitializerTrainingReport,
    QuantileResidualBlock,
    fit_gradient_feature_normalizer,
    flatten_gradient_tuple,
    initialize_direct_prior_from_median,
    pinball_quantile_loss,
    predict_gradient_quantiles,
    quantile_crossing_penalty,
    train_gradient_quantile_network,
)
from .released_gradient_inversion import (
    CandidateReleaseTransformReport,
    ReleasedGradientInversionAttack,
)
from .time_series_regularization import (
    linear_trend_penalty,
    periodicity_penalty,
    resolution_consistency_penalty,
)
from .ts_inverse_style import (
    TS_INVERSE_REFERENCE,
    TSInverseStyleAttack,
    TSInverseStyleComponents,
    joint_forecasting_sequence,
    l1_gradient_distance,
    quantile_bound_hinge_penalty,
    temporal_total_variation_l1,
)

__all__ = [
    "AttackResult",
    "CandidateReleaseTransformReport",
    "GradientFeatureNormalizer",
    "GradientInversionAttack",
    "GradientRelease",
    "GradientReleaseSpec",
    "GradientToQuantileNetwork",
    "HeadRepresentationAttackResult",
    "HeadRepresentationInversionAttack",
    "LEARNED_QUANTILE_REFERENCE",
    "LinearHeadLeakageReport",
    "QuantileInitializerTrainingReport",
    "QuantileResidualBlock",
    "ReleasedGradientInversionAttack",
    "TS_INVERSE_REFERENCE",
    "TSInverseStyleAttack",
    "TSInverseStyleComponents",
    "capture_final_linear_input",
    "clip_gradient_tuple",
    "find_last_biased_linear",
    "fit_gradient_feature_normalizer",
    "flatten_gradient_tuple",
    "gradient_matching_loss",
    "gradient_tuple_l2_norm",
    "infer_class_label_from_last_bias",
    "initialize_direct_prior_from_median",
    "invert_first_linear_gradient",
    "joint_forecasting_sequence",
    "l1_gradient_distance",
    "last_biased_linear_parameter_indices",
    "leak_gradients",
    "linear_trend_penalty",
    "periodicity_penalty",
    "pinball_quantile_loss",
    "predict_gradient_quantiles",
    "quantile_bound_hinge_penalty",
    "quantile_crossing_penalty",
    "quantize_gradient_tuple",
    "recover_single_effective_head_input",
    "release_gradients",
    "resolution_consistency_penalty",
    "temporal_total_variation_l1",
    "train_gradient_quantile_network",
]
