"""Bit-exact quantized models and coherent-oracle compiler backends."""

from .analysis import FiniteIdentifiabilityReport, analyze_finite_oracle
from .anf import ANFOracle, MonomialGate, SynthesisComparison, compare_exact_syntheses
from .arithmetic import (
    AffineRangeReport,
    AffineRowRange,
    ReversibleIntegerAffinePredicateOracle,
    ReversibleIntegerAffineValueOracle,
    affine_range_report,
    append_cdkm_fixed_adder,
    compile_structure_preserving_affine_oracle,
    compile_structure_preserving_threshold_oracle,
)
from .batch_gradient import (
    BatchGradientLayout,
    BatchGradientRangeReport,
    ReversibleBatchGradientEqualityOracle,
    ReversibleBatchGradientValueOracle,
    run_batch_gradient_reconstruction,
)
from .comparators import (
    AffineEqualityLayout,
    ReversibleIntegerAffineEqualityOracle,
    append_equality_to_constant,
    compile_structure_preserving_affine_equality_oracle,
)
from .compiler import (
    MintermGate,
    OracleResourceEstimate,
    TruthTableOracle,
    compile_model_value_oracle,
    compile_verifier_oracle,
)
from .construction_audit import (
    OracleConstructionAudit,
    PreimageIndex,
    audit_anf_oracle,
    audit_structure_preserving_oracle,
    audit_truth_table_oracle,
    build_truth_table_preimage_index,
)
from .costing import (
    ClassicalSearchCosts,
    EndToEndSearchCostReport,
    FaultTolerantGateCosts,
    QuantumSearchCosts,
    QuantumSearchPlan,
    compare_end_to_end_search_costs,
    maximum_t_cost_for_fixed_plan,
    minimum_instances_for_fixed_plan_advantage,
    optimize_quantum_search_plan,
)
from .deep_mlp import (
    DeepMLPHiddenLayout,
    DeepMLPLayout,
    DeepMLPRangeReport,
    DeepMLPResourceBreakdown,
    ReversibleIntegerDeepMLPPredicateOracle,
    compile_structure_preserving_deep_mlp_threshold_oracle,
)
from .fixed_point import (
    FixedPointFormat,
    rescale_code,
    round_half_away_from_zero,
    round_shift_right,
)
from .fixed_point_affine import (
    FixedPointAffineLayout,
    ReversibleFixedPointAffineValueOracle,
    compile_structure_preserving_fixed_point_affine_oracle,
)
from .gradient_arithmetic import (
    GradientArithmeticRangeReport,
    GradientEqualityLayout,
    GradientValueLayout,
    ReversibleSingleRecordGradientEqualityOracle,
    ReversibleSingleRecordGradientValueOracle,
    append_signed_modular_product,
    compile_structure_preserving_gradient_value_oracle,
    gradient_arithmetic_range_report,
    run_structure_preserving_gradient_reconstruction,
)
from .gradient_reconstruction import (
    GradientRangeReport,
    GradientReconstructionReport,
    SingleRecordGradientLeakageSpec,
    recover_single_record_from_full_gradient,
    run_single_record_gradient_reconstruction,
)
from .grover import (
    GroverResourceEstimate,
    GroverSimulationResult,
    estimate_grover_resources,
    simulate_grover,
)
from .mlp import (
    MLPRangeReport,
    MLPResourceBreakdown,
    ReversibleIntegerMLPPredicateOracle,
    ReversibleMLPLayout,
    append_signed_relu_copy,
    compile_structure_preserving_mlp_threshold_oracle,
)
from .models import (
    LayerRangeReport,
    NetworkRangeReport,
    QuantizedAffineLayer,
    QuantizedNetwork,
    quantized_binary_logistic_regression,
)
from .requantization import (
    RequantizationLayout,
    RequantizationRangeReport,
    ReversibleFixedPointRequantizationOracle,
    append_controlled_increment,
    append_controlled_twos_complement,
)
from .reversible import (
    ReversibleCircuit,
    ReversibleGate,
    pack_register,
    unpack_register,
)

__all__ = [
    "ANFOracle",
    "AffineEqualityLayout",
    "AffineRangeReport",
    "AffineRowRange",
    "BatchGradientLayout",
    "BatchGradientRangeReport",
    "ClassicalSearchCosts",
    "DeepMLPHiddenLayout",
    "DeepMLPLayout",
    "DeepMLPRangeReport",
    "DeepMLPResourceBreakdown",
    "EndToEndSearchCostReport",
    "FaultTolerantGateCosts",
    "FiniteIdentifiabilityReport",
    "FixedPointAffineLayout",
    "FixedPointFormat",
    "GradientArithmeticRangeReport",
    "GradientEqualityLayout",
    "GradientRangeReport",
    "GradientReconstructionReport",
    "GradientValueLayout",
    "GroverResourceEstimate",
    "GroverSimulationResult",
    "LayerRangeReport",
    "MLPRangeReport",
    "MLPResourceBreakdown",
    "MintermGate",
    "MonomialGate",
    "NetworkRangeReport",
    "OracleConstructionAudit",
    "OracleResourceEstimate",
    "PreimageIndex",
    "QuantumSearchCosts",
    "QuantumSearchPlan",
    "QuantizedAffineLayer",
    "QuantizedNetwork",
    "RequantizationLayout",
    "RequantizationRangeReport",
    "ReversibleBatchGradientEqualityOracle",
    "ReversibleBatchGradientValueOracle",
    "ReversibleCircuit",
    "ReversibleFixedPointAffineValueOracle",
    "ReversibleFixedPointRequantizationOracle",
    "ReversibleGate",
    "ReversibleIntegerAffineEqualityOracle",
    "ReversibleIntegerAffinePredicateOracle",
    "ReversibleIntegerAffineValueOracle",
    "ReversibleIntegerDeepMLPPredicateOracle",
    "ReversibleIntegerMLPPredicateOracle",
    "ReversibleMLPLayout",
    "ReversibleSingleRecordGradientEqualityOracle",
    "ReversibleSingleRecordGradientValueOracle",
    "SingleRecordGradientLeakageSpec",
    "SynthesisComparison",
    "TruthTableOracle",
    "affine_range_report",
    "analyze_finite_oracle",
    "append_cdkm_fixed_adder",
    "append_controlled_increment",
    "append_controlled_twos_complement",
    "append_equality_to_constant",
    "append_signed_modular_product",
    "append_signed_relu_copy",
    "audit_anf_oracle",
    "audit_structure_preserving_oracle",
    "audit_truth_table_oracle",
    "build_truth_table_preimage_index",
    "compare_end_to_end_search_costs",
    "compare_exact_syntheses",
    "compile_model_value_oracle",
    "compile_structure_preserving_affine_equality_oracle",
    "compile_structure_preserving_affine_oracle",
    "compile_structure_preserving_deep_mlp_threshold_oracle",
    "compile_structure_preserving_fixed_point_affine_oracle",
    "compile_structure_preserving_gradient_value_oracle",
    "compile_structure_preserving_mlp_threshold_oracle",
    "compile_structure_preserving_threshold_oracle",
    "compile_verifier_oracle",
    "estimate_grover_resources",
    "gradient_arithmetic_range_report",
    "maximum_t_cost_for_fixed_plan",
    "minimum_instances_for_fixed_plan_advantage",
    "optimize_quantum_search_plan",
    "pack_register",
    "quantized_binary_logistic_regression",
    "recover_single_record_from_full_gradient",
    "rescale_code",
    "round_half_away_from_zero",
    "round_shift_right",
    "run_batch_gradient_reconstruction",
    "run_single_record_gradient_reconstruction",
    "run_structure_preserving_gradient_reconstruction",
    "simulate_grover",
    "unpack_register",
]
