"""Executable information, collision, query, and cost bounds for Q-RECON."""

from .batch_collisions import (
    BatchCollisionReport,
    LinearBatchGradientObservation,
    construct_linear_batch_collision,
    linear_squared_loss_gradients,
    symmetric_pair_mixing,
    validate_batch_mixing_matrix,
)
from .bounds import (
    all_pairs_epsilon_private_uniform_bound,
    bayes_equivalence_reconstruction_success,
    bayes_reconstruction_success,
    binary_helstrom_success,
    channel_bayes_equivalence_reconstruction_success,
    channel_bayes_reconstruction_success,
    conditional_min_entropy_bits,
    observation_fibres,
    postprocess_channel,
    uniform_fibre_success,
)
from .costs import (
    AlgorithmCost,
    CostComparison,
    compare_algorithm_costs,
    maximum_quantum_query_cost_for_advantage,
    minimum_instances_for_quantum_advantage,
    oracle_error_success_lower_bound,
)
from .search import (
    SearchComparison,
    classical_queries_for_success,
    classical_success_without_replacement,
    compare_search_queries,
    expected_classical_queries,
    grover_queries_for_success,
    grover_success,
    optimal_standard_grover_iterations,
)
from .unknown_k import (
    BBHTEvaluation,
    BBHTRoundReport,
    BBHTSchedule,
    BBHTUniformCertificate,
    build_bbht_schedule,
    certify_bbht_uniform_success,
    evaluate_bbht_schedule,
    randomized_grover_round_success,
)

__all__ = [
    "AlgorithmCost",
    "BBHTEvaluation",
    "BBHTRoundReport",
    "BBHTSchedule",
    "BBHTUniformCertificate",
    "BatchCollisionReport",
    "CostComparison",
    "LinearBatchGradientObservation",
    "SearchComparison",
    "all_pairs_epsilon_private_uniform_bound",
    "bayes_equivalence_reconstruction_success",
    "bayes_reconstruction_success",
    "binary_helstrom_success",
    "build_bbht_schedule",
    "certify_bbht_uniform_success",
    "channel_bayes_equivalence_reconstruction_success",
    "channel_bayes_reconstruction_success",
    "classical_queries_for_success",
    "classical_success_without_replacement",
    "compare_algorithm_costs",
    "compare_search_queries",
    "conditional_min_entropy_bits",
    "construct_linear_batch_collision",
    "evaluate_bbht_schedule",
    "expected_classical_queries",
    "grover_queries_for_success",
    "grover_success",
    "linear_squared_loss_gradients",
    "maximum_quantum_query_cost_for_advantage",
    "minimum_instances_for_quantum_advantage",
    "observation_fibres",
    "optimal_standard_grover_iterations",
    "oracle_error_success_lower_bound",
    "postprocess_channel",
    "randomized_grover_round_success",
    "symmetric_pair_mixing",
    "uniform_fibre_success",
    "validate_batch_mixing_matrix",
]
